package com.safeexam.browser.ui.qrscanner

import androidx.navigation.NavDirections
import com.safeexam.browser.R

/**
 * Safe-args generated class stub.
 * The real implementation is generated by the navigation-safe-args Gradle plugin at build time.
 * This stub exists so the project compiles without the plugin applied in the current context.
 */
object QrScannerFragmentDirections {
    fun actionQrScannerToAddExam(prefilledUrl: String): NavDirections =
        object : NavDirections {
            override val actionId: Int = R.id.action_qrScanner_to_addExam
            override val arguments: android.os.Bundle = android.os.Bundle().apply {
                putString("prefilledUrl", prefilledUrl)
            }
        }
}
