package com.safeexam.browser.ui.addexam

import android.os.Bundle
import androidx.navigation.NavArgs

/**
 * Safe-args generated class stub.
 * The real implementation is generated by the navigation-safe-args Gradle plugin at build time.
 */
data class AddExamFragmentArgs(val prefilledUrl: String = "") : NavArgs {
    companion object {
        @JvmStatic
        fun fromBundle(bundle: Bundle): AddExamFragmentArgs =
            AddExamFragmentArgs(bundle.getString("prefilledUrl") ?: "")
    }
}
